files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/strings.xml
    translate_content: 0
    translate_attributes: 0
    content_segmentation: 0
