name: Generate CHANGELOG.md

on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate Changelog
        uses: tj-actions/github-changelog-generator@v1.15
        with:
          output: "CHANGELOG.md"
      - name: Commit Changelog
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: changelog-bot
          commit_author: Joscha Loos <joscha.loos@rwth-aachen.de>
          commit_message: 'bot: commit changelog.md'
          file_pattern: CHANGELOG.md
          push_options: '--force'
