name: Android Integration Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [21, 23, 29]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
        
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          arch: 'x86_64'
          target: google_apis
          profile: Nexus 6
          # script: ./gradlew connectedAndroidTest --stacktrace
          script: ./gradlew connectedCheck

# jobs:
#   test:
#     runs-on: macos-latest
#     strategy:
#       matrix:
#         api-level: [32]
#     steps:
#       - name: checkout
#         uses: actions/checkout@v3

#       - uses: actions/setup-java@v2
#         with:
#           distribution: 'adopt'
#           java-version: 11

#       - name: run tests
#         uses: reactivecircus/android-emulator-runner@v2
#         with:
#           arch: 'x86_64'
#           target: google_apis
#           api-level: ${{ matrix.api-level }}
#           profile: Nexus 6
#           force-avd-creation: false
#           emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
#           script: ./gradlew connectedAndroidTest --stacktrace
