name: Build & Publish Release APK

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
  

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: setup jdk
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build Release APK
      run: ./gradlew assembleRelease
    - id: get-current-tag
      uses: zingimmick/github-action-get-current-tag@v1
    - name: Release to GitHub
      run: |
        TAG=${{ steps.get-current-tag.outputs.tag }}
        gh release create $TAG -d --generate-notes --latest --target main -t test-release-do-not-use ./app/build/outputs/apk/release/app-release-unsigned.apk
